### ISSUE TITLE
[BUG] FutureWarning when using `to_schema` with a Pandas-like (but not Pandas) obejct

### ISSUE THREAD

**Issue by nprihodko** [fugue-project/triad#127]
**Minimal Code To Reproduce**
Strictly speaking not a bug, just a warning, but this warning is spamming standard output; and could become a bug in the future.

Lets' use Dask data frame as an example of a Pandas-like (but not Pandas) object:

```python
import pandas as pd
from fugue_dask._utils import DASK_UTILS

import dask.dataframe as dd

df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]}, index=[1,2,3])
ddf = dd.from_pandas(df, npartitions=2)
DASK_UTILS.to_schema(ddf)
```
throws warnings:
```
[REDACTED]/.venv/lib/python3.10/site-packages/triad/utils/pandas_like.py:116: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tp = df.dtypes[i]
[REDACTED]/.venv/lib/python3.10/site-packages/triad/utils/pandas_like.py:116: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tp = df.dtypes[i]
```
I believe it's just a matter of changing 
```
tp = df.dtypes[i]
```
to
```python
tp = df.dtypes.iloc[i]
```

**Describe the bug**
When a Pandas-like object is passed to `to_schema`, a FutureWarning is thrown. This does not happen with Pandas data frames, because they do not reach this part of the code.

**Expected behavior**
No warning.

**Environment (please complete the following information):**
 - Backend: pandas/dask
 - Backend version: dask==2024.1.0, pandas==2.1.4
 - Python version: Python 3.10.13
 - OS: macOS.

**Comment by goodwanghan** [comment]
Thank you for reporting, will look into this
