### ISSUE TITLE
[QUESTION] PyFilesystem2 vs fsspec

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/triad#71]
I found this comparison in the [fsspec](https://filesystem-spec.readthedocs.io/en/latest/intro.html) docs so thought to raise it here in case anyone is interested! 

> It might have been conceivable to reuse code in pyfilesystems, which has an established interface and several implementations of its own. However, it supports none of the highlight, critical to cloud and parallel access, and would not be easy to coerce. Following on the success of s3fs and gcsfs, and their use within Dask, it seemed best to have an interface as close to those as possible. See a discussion on the topic.

> Other newer technologies such as smart_open and pyarrow’s newer file-system rewrite also have some parts of the functionality presented here, that might suit some use cases better.

**Comment by rdmolony** [comment]
see also intake/filesystem_spec#5

**Comment by rdmolony** [comment]
I got thinking about this because fsspec supports file caching from s3 on read via s3fs

so I can call 


```python
import fsspec
from fugue import FugueWorkflow
import pandas as pd

of = fsspec.open("filecache::s3://my-bucket/my-file.parquet", filecache={"cache_storage": "data"})

df = pd.read_parquet(of) # caches to data/HASH on first read

with FugueWorkflow() as dag:
    df = dag.load(filepath).show() # fails
```

fugue fails with:

```
_0 _State.RUNNING -> _State.FAILED  .parquet'> is not supported
NotImplementedError: .parquet'> is not supported
```

**Comment by rdmolony** [comment]
I got thinking about this trying to use the fsspec `OpenFile` object with fugue to read and cache a file from s3 via s3fs which proved problematic:

```python
import fsspec
from fugue import FugueWorkflow
import pandas as pd

of = fsspec.open("filecache::s3://codema-dev/my-file.csv", s3={"anon": True}, filecache={"cache_storage": "data"})

df = pd.read_csv(of) # caches to "data/HASH" on first read

with FugueWorkflow() as dag:
    df = dag.load(of).show() # fails with:

# _0 _State.RUNNING -> _State.FAILED  .parquet'> is not supported
# NotImplementedError: .parquet'> is not supported

```

**Comment by rdmolony** [comment]
I can do the same thing easily enough to download the files locally with `pyfilesystem` using https://github.com/PyFilesystem/s3fs

**Comment by goodwanghan** [comment]
I am not sure if you used s3fs in your work. Actually if you install s3fs, pandas will use that to interact with s3. To be honest, this pkg has a lot of issues. For example it has different behaviors (i don't know if I should call them bugs) on fundamental operations on almost every version between 0.2 and 0.4, and then I have to give up. I know pandas is using it through fsspec, it also created some ridiculous issues. For example, if you use spark to save a file to s3, and then with the same process, you will not be able to load that folder of files using pandas+s3fs.

On the other hand, I find the s3fs of PyFileSystems2 is very reliable, and also a lot faster...

To give you another example, I once did an experiment. I uploaded a parquet of 3g to s3. Then use

```python
df = pd.read_parquet("s3://<path>") #s3fs will be used
```
 and use pyfilesystems2

```python
with fs.open("s3://<path>", "rb") as f:
    df = pd.read_parquet(f)
```

The 2nd way is 2-3x faster.

So I am not sure if s3fs is a success at all. And highlights are not as convincing as reliable performance I got from pyfilesystems2.

**Comment by rdmolony** [comment]
Thanks Han, that clears it up. I do like how s3fs hides behind pandas and dask letting them just receive a URL, so raised it in case you hadn’t come across it!

**Comment by benlindsay** [comment]
Hey @rdmolony and @goodwanghan, I'm trying to find resources that compare pyfilesystem and fsspec, and there's not much out there. It seems from this issue that PyFilesystem2 is better for your use case? Are there any uses cases where you'd consider using fsspec instead?

**Comment by goodwanghan** [comment]
> Hey @rdmolony and @goodwanghan, I'm trying to find resources that compare pyfilesystem and fsspec, and there's not much out there. It seems from this issue that PyFilesystem2 is better for your use case? Are there any uses cases where you'd consider using fsspec instead?

Actually, Fugue is an abstraction layer, and we can't stop the underlying frameworks from using fsspec, for example pandas will use it. For the explicit part where Fugue has to directly interact with filesystems, it's all based on PyFileSystem2. Notice that, the direct interaction from Fugue to filesystems requires only basic operations, so we need a solution that is extremely solid and consistent on basic file operations. And we find PyFileSystem is superior on this, and also faster.

Fsspec has advanced operations, for example you can read a file from an offset, and as well as asynchronous operations. They can be very useful for users who are dealing with large data from a single machine. But when you want to interact with large files or large quantity of files from a single machine, why not consider a truly distributed approach instead? If you are bounded by a single machine, it can't scale well no matter how asynchronous and flexible a filesystem framework can give you.

But that is just my opinion, and as for Fugue, it uses PyFileSystems2 explicitly and fsspec implicitly.

**Comment by benlindsay** [comment]
Got it, thanks! One major detail I hadn't noticed is that it looks like Pyfilesystem2 doesn't seem to support Azure Blob Storage yet, which, if true, would be a deal breaker for me
