### ISSUE TITLE
[QUESTION] What does save with scheme mean?

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/triad#75]
When saving a file to a relative filepath such as the current working directory `Fugue` raises:

```
ValueError: invalid , must be abs path either local or with scheme 
```

**Comment by rdmolony** [comment]
Ref #73 #74

**Comment by rdmolony** [comment]
Does it mean save to `s3://my-bucket/my-file.csv`?

**Comment by kvnkho** [comment]
Yes that is right. All paths in Fugue are absolute or for s3 specifically, you need the scheme, which is `s3`
