### ISSUE TITLE
[FEATURE] Support nested types in `triad.utils.pyarrow.expression_to_schema`

### ISSUE THREAD

**Issue by deepyaman** [fugue-project/triad#88]
**Is your feature request related to a problem? Please describe.**

Over at https://github.com/kedro-org/kedro, we've got a need to be able to specify a PyArrow schema argument in YAML. From what we can tell, PyArrow doesn't natively support defining lists/dicts/etc., so I found Fugue. However, as @avsolatorio pointed out, Fugue doesn't seem to support nested object. I think it could be pretty trivial, though?

**Describe the solution you'd like**
See #89 

For example:

```python
>>> from triad.utils.pyarrow import expression_to_schema
>>> expression_to_schema("a:[[int]]")
a: list<item: list<item: int32>>
  child 0, item: list<item: int32>
      child 0, item: int32
```

Happy to add tests; just wanted to raise the issue first to see if such a change were even welcome.

**Describe alternatives you've considered**
Rolling our own parser.

**Additional context**

> I don't think PyArrow provides a native way to define complex schema as text (as mentioned in your issue), although simple stuff like `pa.schema({'hi': 'u1'}) == pa.schema({'hi': pa.uint8()})` works. However, [Fugue](https://fugue-tutorials.readthedocs.io/tutorials/advanced/schema_dataframes.html#schema) provides a way to do so. Maybe we should just use their logic, since it's non-trivial? The requirements for https://github.com/fugue-project/triad also look pretty lightweight, so I don't see an issue with depending on it.

@deepyaman thanks for looking into this! I checked Fugue, and I don't think it supports complex schema structures such as nested list types. For example, I don't see any way to represent a field that has this representation `list_(list_(int64))`.

I have implemented a parser instead to supplant the use of `eval`, and I think it works relatively well.

_Originally posted by @avsolatorio in https://github.com/kedro-org/kedro/issues/1746#issuecomment-1201945358_

**Comment by goodwanghan** [comment]
@deepyaman I apologize for the late reply. Actually, we do support nested structures, and `[[int]]` is a bug I was about to fix but you just found it!!

If you want to see examples, you can see our unit tests, they cover a lot of scenarios: https://github.com/fugue-project/triad/blob/4db874be805334e4c58f27ccf16a80358386d4d2/tests/utils/test_pyarrow_convert.py#L159-L205

For your PR, can you add a test of `[[int]]` into the tests to make sure this bug is resolved?

**Comment by deepyaman** [comment]
> @deepyaman I apologize for the late reply. Actually, we do support nested structures, and `[[int]]` is a bug I was about to fix but you just found it!!
> 
> If you want to see examples, you can see our unit tests, they cover a lot of scenarios:
> 
> https://github.com/fugue-project/triad/blob/4db874be805334e4c58f27ccf16a80358386d4d2/tests/utils/test_pyarrow_convert.py#L159-L205
> 
> For your PR, can you add a test of `[[int]]` into the tests to make sure this bug is resolved?

Happy to. Thanks for taking a look!

**Comment by goodwanghan** [comment]
@deepyaman 0.6.7 has been released, thank you so much!
